### ISSUE TITLE
Need to add additional buckets to the codebuild iam role

### ISSUE THREAD

**Issue by hussfelt** [squidfunk/terraform-aws-github-ci#7]
https://github.com/squidfunk/terraform-aws-github-ci/blob/56e3a3b59f9c026e9e91cca279d13a6d73676fb7/share/iam/policies/codebuild.json#L22

Hey,

I have some needs to push additional resources to another bucket in my build.
Any ideas on how to accomplish that?
If you do - let me know, and I'll implement :)

**Comment by squidfunk** [comment]
The codebuild role is exported as an output:

https://github.com/squidfunk/terraform-aws-github-ci/blob/56e3a3b59f9c026e9e91cca279d13a6d73676fb7/outputs.tf#L30-L33

You could use it to attach further policies like this:

https://github.com/squidfunk/terraform-aws-github-ci/blob/56e3a3b59f9c026e9e91cca279d13a6d73676fb7/main.tf#L71-L85

**Comment by hussfelt** [comment]
Yeah, I realised that the morning after :-) Thanks again for this beautiful module! 👍🏻🎉
